[package]
name = "ray_track"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
progress_bar = "1.0.2"
PMXUtil = "0.9.0"
rand="0.3.17"
hexasphere = "7.2.1"
cgmath = "0.18.0"